masifapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import logout
from django.urls import path, include

from masifapp import settings

urlpatterns = [
    path('', include('landing.urls')),
    path('cari-lowongan/', include('cari_lowongan.urls')),
    path('admin/', include('admin.urls')),
    path('opd/', include('opd.urls')),
    path('lowongan/', include('lowongan.urls')),
    path('account-redirector', include('account_redirector.urls')),
    path('superuser/', admin.site.urls),
    #     # path('auth/', include('social_django.urls')),
    #     # TESTING PATH dibawah ini
    #     path('user/', include('google_oauth2.urls')),
    path('user/', include('user.urls')),
    path('kesbangpol/', include('kesbangpol.urls')),
    path('artikel/', include('artikel.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opd/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views

urlpatterns = [
    path('', views.opd_home, name='opd_home'),
    path('sorting/waktu-magang/<str:param>', views.sort_by_waktu_magang),
    path('sorting/batas-akhir/<str:param>', views.sort_by_batas_akhir),
    path('searching/<str:param>', views.search_by_judul),
    path('lowongan/list-pendaftar-selesai-<str:id_lowongan>/', views.opd_list_pendaftar_selesai),
    path('lowongan/buka-tutup/<str:id_lowongan>/', views.opd_tutup_lowongan, name='opd_tutup_lowongan'),
    path('proses-<str:id_user>-<str:id_lowongan>/<str:status>/<str:catatan>/', views.opd_update_lamaran,
         name='opd_update_lamaran'),
    path('lowongan/file_tambahan-<str:id_user>-<str:id_lowongan>/', views.opd_download_file, name='opd_download_file'),
    path('lowongan/cv_pendaftar-<str:id_user>-<str:id_lowongan>/', views.opd_download_cv, name='opd_download_cv'),
    path('lowongan/list-pendaftar-<str:id_lowongan>/', views.opd_list_pendaftar, name='opd_list_pendaftar'),
    path('lowongan/detail-<str:id_lowongan>/', views.opd_detail_lowongan, name='opd_detail_lowongan'),
    path('verification/404', views.opd_verification_not_found,
         name='opd_verification_not_found'),
    path('verification/<str:token>',
         views.opd_verification, name='opd_verification'),
    path('verification/',
         views.opd_verification_redirect, name='opd_verification_redirect'),
    path('editprofile/<int:pk>/',
         views.opd_edit_profile_view, name='opd_edit_profile_view'),
    path('editprofile/<int:pk>/post/',
         views.opd_edit_profile_handler, name='opd_edit_profile_post'),
    path('editprofile/<int:pk>/post/upload_profile_picture/', views.upload_profile_picture_opd,
         name='opd_edit_upload_pp'),

]

account/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models


class AccountManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have email address")

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        if not email:
            raise ValueError("Users must have email address")

        user = self.create_user(
            email=self.normalize_email(email),
            password=password)
        user.name = "SuperUser"
        user.phone = "000"
        user.is_superuser = True
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    profile_picture = models.FileField(
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=128)
    email = models.EmailField(
        verbose_name="email", max_length=254, unique=True)
    phone = models.CharField(max_length=26)
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_kesbangpol = models.BooleanField(default=False)
    is_opd = models.BooleanField(default=False)
    is_user = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = AccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True


class OpdProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank=False
    )
    # Temporary Attribute
    unique_opd_attribute = models.CharField(max_length=60)
    address = models.CharField(null=False, blank=False, max_length=120, default="Belum ada alamat")

    def __str__(self):
        return "<OPD Profile> {}".format(self.unique_opd_attribute)


class AdminProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank=False
    )
    # Temporary Attribute
    unique_admin_attribute = models.CharField(max_length=60)

    def __str__(self):
        return "<ADMIN Profile> {}".format(self.unique_admin_attribute)


class UserProfile(models.Model):
    DEFAULT_NOT_SET = 'Not set'

    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True,
        null=False,
        blank=False,
    )

    born_date = models.DateField(default=datetime(1945, 8, 17))
    born_city = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    address = models.CharField(default=DEFAULT_NOT_SET, max_length=300)
    '''
    *sex types*
    m = male
    f = female
    n = not set
    '''
    sex = models.CharField(default='n', max_length=1)
    education = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    institution = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    major = models.CharField(default=DEFAULT_NOT_SET, max_length=120)
    cv = models.FileField(
        null=True,
        blank=True,
    )
    # Temporary Attribute
    unique_pelamar_attribute = models.CharField(max_length=60, default='a')

    def __str__(self):
        return "<USER Profile> Account : {}".format(self.user.email)


class PelamarProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank="False"
    )
    # Temporary Attribute
    unique_pelamar_attribute = models.CharField(max_length=60)

    def __str__(self):
        return "<PELAMAR Profile> {}".format(self.unique_pelamar_attribute)


class KesbangpolProfile(models.Model):
    user = models.OneToOneField(
        Account,
        on_delete=models.CASCADE,
        primary_key=True, null=False, blank=False
    )
    # Temporary Attribute
    unique_kesbangpol_attribute = models.CharField(max_length=60)

    def __str__(self):
        return "<KESBANGPOL Profile> {}".format(
            self.unique_kesbangpol_attribute)

opd/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from account.models import Account, OpdProfile
from admin.models import OpdVerificationList
from lowongan.models import Lowongan
from lowongan.models import UserLamarMagang
from user.forms import ProfilePictureForm
from .forms import EditOpdProfileForm
from .opd_confirmation_form import OpdConfirmationForm

opd_home = '/opd/'
home = '/'

template_opd_lowongan = 'opd_lowongan.html'


def sort_by_waktu_magang(request, param):
    filter_obj = Lowongan.objects.filter(opd_foreign_key=request.user.id)
    if request.method == 'GET':
        response = {}
        if param == 'asc':
            obj_lowongan = filter_obj.order_by('waktu_awal_magang')
            response['data'] = obj_lowongan
            return render(request, template_opd_lowongan, response)
        elif param == 'desc':
            obj_lowongan = filter_obj.order_by('-waktu_awal_magang')
            response['data'] = obj_lowongan
            return render(request, template_opd_lowongan, response)
        else:
            return redirect(opd_home)
    else:
        return redirect(opd_home)


def sort_by_batas_akhir(request, param):
    filter_obj = Lowongan.objects.filter(opd_foreign_key=request.user.id)
    if request.method == 'GET':
        response = {}
        if param == 'asc':
            obj_lowongan = filter_obj.order_by('batas_akhir_pendaftaran')
            response['data'] = obj_lowongan
            return render(request, template_opd_lowongan, response)
        elif param == 'desc':
            obj_lowongan = filter_obj.order_by('-batas_akhir_pendaftaran')
            response['data'] = obj_lowongan
            return render(request, template_opd_lowongan, response)
        else:
            return redirect(opd_home)
    else:
        return redirect(opd_home)


def search_by_judul(request, param):
    if request.method == 'GET':
        response = {}
        obj_lowongan = Lowongan.objects.filter(
            judul__contains=param).order_by('judul')
        response['data'] = obj_lowongan
        return render(request, template_opd_lowongan, response)
    else:
        return redirect(opd_home)


def opd_login(request):
    return render(request, 'opd_login.html')


@csrf_exempt
def opd_update_lamaran(request, id_lowongan, id_user, status, catatan):
    try:
        userlamarmagang = UserLamarMagang.objects.get(user_foreign_key=id_user, lowongan_foreign_key=id_lowongan)
        if (cek_id_lowongan_dan_opd(request, id_lowongan) and userlamarmagang.status_kesbangpol != 'DITERIMA'):
            userlamarmagang.status_lamaran = status
            userlamarmagang.notes_status_lamaran = catatan
            userlamarmagang.save()
            return redirect('/opd/lowongan/list-pendaftar-' + id_lowongan + '/')
        else:
            return redirect(opd_home)
    except ObjectDoesNotExist:
        return redirect(opd_home)


def opd_list_pendaftar(request, id_lowongan):
    # cek apakah user sudah login dan user harus opd
    if request.user.is_authenticated and request.user.is_opd:
        if (cek_id_lowongan_dan_opd(request, id_lowongan)):
            lowongan = Lowongan.objects.get(id=id_lowongan)
            lamaran = UserLamarMagang.objects.filter(lowongan_foreign_key=id_lowongan , status_kesbangpol = "MENUNGGU_OPD")
            return render(request, 'opd_list_pendaftar.html',
                          {'lowongan': lowongan,
                           'lamaran': lamaran
                           })
        else:
            return redirect(opd_home)
    else:
        return redirect(home)

def opd_list_pendaftar_selesai(request , id_lowongan):
    try:
        if request.user.is_authenticated and request.user.is_opd:
            if (cek_id_lowongan_dan_opd(request, id_lowongan)):
                lowongan = Lowongan.objects.get(id=id_lowongan)
                lamaran = UserLamarMagang.objects.filter(lowongan_foreign_key=id_lowongan , status_kesbangpol = 'DITERIMA')
                return render(request, 'opd_list_pendaftar.html',
                            {'lowongan': lowongan,
                            'lamaran': lamaran
                            })
            else:
                return redirect(opd_home)
        else:
            return redirect(home)
    except ObjectDoesNotExist:
        return redirect(opd_home)



def opd_download_file(request, id_user, id_lowongan):
    try:
        userlamarmagang = UserLamarMagang.objects.get(user_foreign_key=id_user, lowongan_foreign_key=id_lowongan)
        if (cek_id_lowongan_dan_opd(request, id_lowongan)):
            filename = userlamarmagang.file_berkas_tambahan.name.split('/')[-1]
            if (userlamarmagang.file_berkas_tambahan):
                response = HttpResponse(userlamarmagang.file_berkas_tambahan, content_type='text/plain')
                response['Content-Disposition'] = 'attachment; filename=%s' % filename
                return response
            else:
                return HttpResponse('tidak ada file')
        else:
            return redirect(opd_home)
    except ObjectDoesNotExist:
        return redirect(opd_home)


def opd_download_cv(request, id_user, id_lowongan):
    try:
        if (cek_id_lowongan_dan_opd(request, id_lowongan)):
            pelamar = Account.objects.get(id=id_user)
            if (pelamar.userprofile.cv):
                filename = pelamar.userprofile.cv.name.split('/')[-1]
                response = HttpResponse(pelamar.userprofile.cv, content_type='text/plain')
                response['Content-Disposition'] = 'attachment; filename=%s' % filename
                return response
            else:
                return HttpResponse('tidak ada file')
        else:
            return redirect(opd_home)
    except ObjectDoesNotExist:
        return redirect(opd_home)


# Fungsi untuk mengecek apakah opd yang
# mengakses data lowongan adalah opd terkait
def cek_id_lowongan_dan_opd(request, id_lowongan):
    try:
        lowongan = Lowongan.objects.get(id=id_lowongan)
        if (lowongan.opd_foreign_key_id == request.user.id):
            return True
        else:
            return False
    except ObjectDoesNotExist:
        return False


def opd_home(request):
    if request.user.is_authenticated and request.user.is_opd:
        data = Lowongan.objects.filter(opd_foreign_key=request.user.id)

        return render(request, 'opd_lowongan.html', {'data': data})
    else:
        return redirect(home)


def opd_detail_lowongan(request, id_lowongan):
    if cek_id_lowongan_dan_opd(request, id_lowongan):
        lowongan = Lowongan.objects.get(id=id_lowongan)
        return render(request, 'opd_detail_lowongan.html', {'lowongan': lowongan})
    else:
        return redirect(home)


def opd_tutup_lowongan(request, id_lowongan):
    if cek_id_lowongan_dan_opd(request, id_lowongan):
        lowongan = Lowongan.objects.get(id=id_lowongan)
        lowongan.is_lowongan_masih_berlaku = not (lowongan.is_lowongan_masih_berlaku)
        lowongan.save()
        return redirect(opd_home)
    else:
        return redirect(home)


def opd_verification(request, token):
    try:
        opd_from_verification_list = OpdVerificationList.objects.get(
            secret=token)
        opd_name = opd_from_verification_list.name
        email = opd_from_verification_list.email
        phone = opd_from_verification_list.phone
    except OpdVerificationList.DoesNotExist:
        return redirect('/opd/verification/404')
    if request.method == 'POST':
        form = OpdConfirmationForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            new_user = Account.objects.create_user(email, password)
            new_user.name = opd_name
            new_user.phone = phone
            new_user.is_opd = True
            new_user.save()
            print(password)
            print(new_user.password)
            create_opd = OpdProfile(user=new_user, unique_opd_attribute="opd")
            create_opd.save()
            opd_from_verification_list.delete()
            return redirect("/user/login")
    else:
        form = OpdConfirmationForm()
    return render(
        request,
        'opd/opd_verification.html',
        {
            'token': token,
            'form': form,
            'opd_name': opd_name
        }
    )


def opd_verification_not_found(request):
    return render(
        request,
        'opd/opd_verification_404.html'
    )


def opd_verification_redirect(request):
    return redirect("/")


OPD_DASHBOARD = '/opd/'


def opd_edit_profile_handler(request, pk):
    if is_permitted_to_edit(request, pk) and request.method == 'POST':
        form = EditOpdProfileForm(request.POST)

        if form.is_valid():
            account_obj = Account.objects.get(pk=pk)
            account_obj.name = request.POST['name']
            account_obj.phone = request.POST['phone']
            account_obj.opdprofile.address = request.POST['address']
            account_obj.opdprofile.save()
            account_obj.save()
            if request.user.is_admin:
                return redirect('/admin/listopd/')
            return redirect(OPD_DASHBOARD)

        return HttpResponse(form.errors)
    else:
        return HttpResponse("Access Denied")


def upload_profile_picture_opd(request, pk):
    if is_permitted_to_edit(request, pk) and request.method == 'POST':
        form = ProfilePictureForm(request.POST, request.FILES)
        if form.is_valid():
            to_be_edited_user = Account.objects.get(pk=pk)
            to_be_edited_user.profile_picture = request.FILES['profile_picture']
            to_be_edited_user.save()

        return redirect('/opd/editprofile/{}/'.format(pk))
    return HttpResponse("ERROR No Permission")


def is_permitted_to_edit(req, pk):
    return req.user.is_authenticated and (

templates/opd/opd-edit-profile.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="/static/css/user/user-profile-detail-dashboard.css">

    <link rel="stylesheet" href="/static/css/opd-edit-profile.css">
    <title>Edit Profil OPD</title>

{% endblock %}
{% block body %}
    {% include 'navbar-no-bootstrap.html' %}
    <div class="container">
        {% if permitted %}
            <h2 class="page-title text-center">Edit Profil OPD</h2>

            <div class="row">
                <div class="input-wrapper col-12 col-sm-1 col-md-2"></div>
                <div class="input-wrapper col-12 col-sm-10 col-md-8">
                    <div id="profile-picture-col" class="col-12 col-sm-auto">
                        <span id="foto-keterangan">Klik untuk ganti foto</span>
                        <div class="image-upload">
                            <label for="id_profile_picture">

                                {% if account_obj.profile_picture %}
                                    <img style="image-orientation: flip;" id="profile_picture"
                                         src="/media/{{ account_obj.profile_picture }}" alt="pp">
                                {% else %}
                                    <img id="profile_picture" src="/static/img/add_photo.png" alt="pp">
                                {% endif %}

                            </label>
                            <form id="form-profile-picture" method="post" enctype="multipart/form-data"
                                  action="{% url 'opd_edit_upload_pp' account_obj.pk %}">
                                {% csrf_token %}
                                <span style="display: none">{{ photo_form.profile_picture }}</span>

                            </form>

                        </div>
                    </div>
                    <p>Email : <br>{{ account_obj.email }}</p>
                    <form action="/opd/editprofile/{{ account_obj.pk }}/post/" method="post">
                        {% csrf_token %}

                        {{ form }}
                        <div id="submit-wrapper">

                            <button id="submit-button" class="ml-auto btn btn-primary" type="submit">
                                Submit
                            </button>
                        </div>

                    </form>
                </div>
                <div class="input-wrapper col-12 col-sm-1 col-md-2"></div>
            </div>

        {% else %}
            <!-- Error handling for permission -->
            <h1 class="page-title text-center">BUKAN OPD TIDAK PERMITTED</h1>
        {% endif %}

    </div>

    <script>
        document.getElementById("id_profile_picture").onchange = function () {
            document.getElementById("form-profile-picture").submit();
        };

    </script>
{% endblock %}

templates/opd/opd_verification.html
{% extends 'base.html' %}
{% block head %}
    <title>Verifikasi OPD</title>
{% endblock %}

{% block body %}
{% include 'navbar-no-bootstrap.html' %}
<div class="container-fluid">
    <div class="row justify-content-center" style="height: 100vh">
        <div class="col-4 align-self-center">
            <form method="POST" action="{% url 'opd_verification' token %}"
            oninput='id_confirm_password.setCustomValidity(id_confirm_password.value != id_password.value ? "Passwords do not match." : "")'
            >
                {% csrf_token %}
                <h1 class="admin-login-items">Verifikasi OPD</h1>
                <h4 class="opd-name">Nama OPD: {{ opd_name }}</h4>
                <label>Password : </label>
                {{ form.password }}
                <label>Ulangi Password : </label>
                {{ form.confirm_password }}

            <br>
                <button type="submit" class="btn btn-primary admin-login-items" id="submit-btn">Submit</button>

            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/opd/opd_verification_404.html
{% extends 'base.html' %}
{% block head %}
    <title>Verifikasi OPD</title>
{% endblock %}
{% block body %}
{% include 'navbar-no-bootstrap.html' %}
<div class="container-fluid">
    <div class="row justify-content-center" style="height: 100vh">
        <div class="col-6 align-self-center">
            <h1>Token not found,<a href="/"> Please contact admin</a></h1>
        </div>
    </div>
</div>
{% endblock %}